using NugsDownloader.App.UseCases;
using NugsDownloader.Domain.ValueObjects;
using Xunit;

namespace NugsDownloader.Tests;

public class StartDownloadRequestTests
{
    [Fact]
    public void StartDownloadRequest_UsesSuppliedFields()
    {
        var request = new StartDownloadRequest(
            JobId: Guid.Parse("00000000-0000-0000-0000-000000000001"),
            ProviderId: "nugs",
            SourceUrl: new Uri("https://play.nugs.net/release/99"),
            Credentials: new Credentials("user", "token", "token-value"),
            Preferences: new DownloadPreferences("flac", "1080p", false, false, false, "Downloads", true, true));

        Assert.Equal("nugs", request.ProviderId);
        Assert.Equal(new Uri("https://play.nugs.net/release/99"), request.SourceUrl);
        Assert.Equal("user", request.Credentials.Username);
    }

    [Fact]
    public void StartDownloadRequest_SupportsAutoGeneratedJobId()
    {
        var request = new StartDownloadRequest(
            JobId: null,
            ProviderId: null,
            SourceUrl: new Uri("https://play.nugs.net/release/100"),
            Credentials: new Credentials("user", "token", "token-value"),
            Preferences: new DownloadPreferences(null, null, true, true, false, "Downloads", true, true));

        Assert.Null(request.JobId);
        Assert.Null(request.ProviderId);
        Assert.Equal("https://play.nugs.net/release/100", request.SourceUrl.ToString());
        Assert.True(request.Preferences.SkipVideos);
    }
}
